// <auto-generated />
using System;
using Dershane.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dershane.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dershane.Models.Anasayfa_icerik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anasayfa_Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Anasayfa_Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Anasayfa_icerik");
                });

            modelBuilder.Entity("Dershane.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Banner_Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Banner_Gorsel_Tipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Banner_Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Gorsel_Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("Dershane.Models.DokumanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dokuman_Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dokuman_Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Dokumanlar");
                });

            modelBuilder.Entity("Dershane.Models.Duyurular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duyuru_Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duyuru_Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Duyuru_Tarih")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Duyurular");
                });

            modelBuilder.Entity("Dershane.Models.EgitimModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EgitimAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EgitimAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Egitimler");
                });

            modelBuilder.Entity("Dershane.Models.Etkinlikler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Etkinlik_Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etkinlik_Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Etkinlik_Tarih")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Etkinlikler");
                });

            modelBuilder.Entity("Dershane.Models.Haberler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Haber_Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haber_Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Haber_Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Haberler");
                });

            modelBuilder.Entity("Dershane.Models.Hakkimizda_icerik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Hakkimizda_Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hakkimizda_Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hakkimizda_icerik");
                });

            modelBuilder.Entity("Dershane.Models.IletisimModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Iletisim");
                });

            modelBuilder.Entity("Dershane.Models.Kadromuz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kadromuz");
                });

            modelBuilder.Entity("Dershane.Models.KurumsalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Kurumsal_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Logo_Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Logo_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel_No")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KurumsalBilgiler");
                });

            modelBuilder.Entity("Dershane.Models.SubelerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Gorsel_Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SubeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubeKonum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subeler");
                });
#pragma warning restore 612, 618
        }
    }
}
